Repository felipecolodiano/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#5 Create requisitos.md
  docs/requisitos.md
Labels: análise

#6 Integrar testes v1.0
  src/testes_inic.py
  src/testes_jogar.py
Labels: testes

#7 Create jogovelha.py
  src/jogovelha.py
Labels: programação

#8 Integra arquitetura v1.0
  docs/arquitetura.md
Labels: arquitetura

#9 Gerar release v1.0
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
  src/testes_inic.py
  src/testes_jogar.py
Labels: operações

#16 Update requisitos.md
  docs/requisitos.md
Labels: análise

#15 Integrar arquitetura v1.1
  docs/arquitetura.md
Labels: arquitetura

#17 Update jogovelha.py
  src/jogovelha.py
Labels: programação

#18 Testar inicialização do tabuleiro V1.1
  src /testes_inic.py
  src/testes-jogar.py
Labels: testes
